<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:22.
 */
class InvalidFieldsFieldExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidFieldsFieldException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidFieldsFieldException
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Fields: badKey is invalid. Valid fields are: goodKey
     */
    public function testThrowInvalidFieldsFieldException()
    {
        $invalidKeys = ['badKey'];
        $validKeys = ['goodKey'];
        throw New InvalidFieldsFieldException($invalidKeys, $validKeys);
    }

    protected function tearDown()
    {
        
    }
}
