<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:22.
 */
class InvalidFilterValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidFilterValue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

     /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidFilterValue
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Value badKey is not a valid value for key. Valid values are goodKey
     */
    public function testThrowInvalidFilterValue()
    {
        $invalidKeys = ['badKey'];
        $validKeys = ['goodKey'];
        $key = 'key';
        throw New InvalidFilterValue($invalidKeys, $key, $validKeys);
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
