<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:22.
 */
class InvalidFilterFieldExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidFilterFieldException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidFilterFieldException
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Filter key: badKey is invalid. Valid keys are: goodKey
     */
    public function testThrowInvalidFilterFieldException()
    {
        $invalidKeys = 'badKey';
        $validKeys = ['goodKey'];
        throw New InvalidFilterFieldException($invalidKeys, $validKeys);
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
