<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-02 at 05:34:43.
 */
class InvalidFilterKeyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidFilterKey
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {   
    }
    /**
     * @expectedExceptionCode 400
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidFilterKey
     */
    public function testInvalidFilterKey(){
        throw new InvalidFilterKey(['badKey'],['goodKey']);
    }
}
