<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:23.
 */
class InvalidOrderKeyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidOrderKey
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidOrderKey
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Order field:badKey is invalid. Valid fields are: goodKey
     */
    public function testThrowInvalidOrderKey()
    {
        $invalidKeys = 'badKey';
        $validKeys = ['goodKey'];
        throw New InvalidOrderKey($invalidKeys, $validKeys);
    }

    /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidOrderKey
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Order field:c is invalid. Valid fields are: a,b
     */
    public function testThrowInvalidOrderSingleKey()
    {
        $invalidKeys = 'c';
        $validKeys = ['a','b'];
        throw New InvalidOrderKey($invalidKeys, $validKeys);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
