<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:23.
 */
class InvalidAliasKeyExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InvalidAliasKeyException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    
    /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\InvalidAliasKeyException
     * @expectedExceptionCode 400
     * @expectedExceptionMessage Alias Key(s):badKey are invalid. Valid keys are: goodKey
     */
    public function testThrowInvalidAliasKeyException()
    {
        $invalidKeys = ['badKey'];
        $validKeys = ['goodKey'];
        throw New InvalidAliasKeyException($invalidKeys, $validKeys);
    }
    
    protected function tearDown()
    {
        
    }
}
