<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:23.
 */
class MissingPayloadKeyExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MissingPayloadKeyException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }
    
        /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\MissingPayloadKeyException
     * @expectedExceptionCode 422
     * @expectedExceptionMessage Field:b is missing. Required fields are: a,b
     */
    public function testThrowMissingPayloadKeyException()
    {
        $invalidKeys = ['b'];
        $validKeys = ['a','b'];
        throw New MissingPayloadKeyException($invalidKeys, $validKeys);
    }
    

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
