<?php namespace CTIMT\MyOrm\Exception\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:23.
 */
class NonComittableExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var NonComittableException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NonComittableException;
    }
      /**
     * @expectedException CTIMT\MyOrm\Exception\Adapter\NonComittableException
     * @expectedExceptionCode 0
     * @expectedExceptionMessage 
     */
    public function testThrowNonComittableException()
    {
        throw New NonComittableException();
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
