<?php namespace CTIMT\MyOrm\Enum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 23:17:28.
 */
class ErrorMessagesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ErrorMessages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorMessages;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Enum\ErrorMessages::InvalidDataType
     * @todo   Implement testInvalidDataType().
     */
    public function testInvalidDataType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
