<?php

namespace CTIMT\MyOrm\Enum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 23:17:29.
 */
class FormatsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Formats
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Formats;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
