<?php namespace CTIMT\MyOrm\Enum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 23:17:34.
 */
class SortKeysTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SortKeys
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SortKeys;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
