<?php namespace CTIMT\MyOrm\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 15:49:20.
 */
class DefaultValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DefaultValue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultValue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\DefaultValue::visitModel
     * @todo   Implement testVisitModel().
     */
    public function testVisitModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\DefaultValue::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
