<?php namespace CTIMT\MyOrm\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 15:49:19.
 */
class PaginationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Pagination
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pagination;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::visitSelect
     * @todo   Implement testVisitSelect().
     */
    public function testVisitSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::visitModel
     * @todo   Implement testVisitModel().
     */
    public function testVisitModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::addMetaInformationToLayout
     * @todo   Implement testAddMetaInformationToLayout().
     */
    public function testAddMetaInformationToLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::setTotals
     * @todo   Implement testSetTotals().
     */
    public function testSetTotals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::getPageSize
     * @todo   Implement testGetPageSize().
     */
    public function testGetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::getPage
     * @todo   Implement testGetPage().
     */
    public function testGetPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::getTotalResults
     * @todo   Implement testGetTotalResults().
     */
    public function testGetTotalResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::getTotalPages
     * @todo   Implement testGetTotalPages().
     */
    public function testGetTotalPages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::setPageSize
     * @todo   Implement testSetPageSize().
     */
    public function testSetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::setPage
     * @todo   Implement testSetPage().
     */
    public function testSetPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::setTotalResults
     * @todo   Implement testSetTotalResults().
     */
    public function testSetTotalResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\Pagination::setTotalPages
     * @todo   Implement testSetTotalPages().
     */
    public function testSetTotalPages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
