<?php namespace CTIMT\MyOrm\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 15:49:18.
 */
class StaticValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var StaticValue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StaticValue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testVisitModel()
    {

    }


    public function testUpdate()
    {

    }
    
    public function testEventNames()
    {
        $value = ['test'];
        $this->assertEquals($value,$this->object->setEventNames($value)->getEventNames());
    }
    
    public function testApplyStaticValues(){
        $data = ['data'=>'value','overridden'=>'neverSeeMe'];
        $staticData = ['overridden'=>'good Data'];
        $output = ['data'=>'value','overridden'=>'good Data'];
        $this->assertEquals($output,$this->object->applyStaticValues($data, $staticData));
    }
    
    public function testApplyStaticValuesAddition(){
        $data = ['data'=>'value','extraField'=>'extraValue'];
        $staticData = ['static'=>'good Data'];
        $output = ['data'=>'value','extraField'=>'extraValue','static'=>'good Data'];
        $this->assertEquals($output,$this->object->applyStaticValues($data, $staticData));
    }
}
