<?php namespace CTIMT\MyOrm\Exception\Platform;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:26.
 */
class BadMethodCallExceptionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException BadMethodCallException
     * @expectedExceptionMessage someMessage
     */
    public function testBadMethodCallException()
    {
        throw New BadMethodCallException('someMessage');
    }
}
