<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:26.
 */
class DomainExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException DomainException
     * @expectedExceptionMessage someMessage
     */
    public function testDomainException()
    {
        throw New DomainException('someMessage');
    }

}
