<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:25.
 */
class LengthExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException LengthException
     * @expectedExceptionMessage someMessage
     */
    public function testLengthException()
    {
        throw New LengthException('someMessage');
    }

}
