<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:25.
 */
class LogicExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException LogicException
     * @expectedExceptionMessage someMessage
     */
    public function testLogicException()
    {
        throw New LogicException('someMessage');
    }
}
