<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:27.
 */
class OutOfRangeExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException OutOfRangeException
     * @expectedExceptionMessage someMessage
     */
    public function testOutOfRangeException()
    {
        throw New OutOfRangeException('someMessage');
    }
}
