<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:25.
 */
class OutOfBoundsExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException OutOfBoundsException
     * @expectedExceptionMessage someMessage
     */
    public function testOutOfBoundsException()
    {
        throw New OutOfBoundsException('someMessage');
    }
}
