<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:24.
 */
class RangeExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException RangeException
     * @expectedExceptionMessage someMessage
     */
    public function testRangeException()
    {
        throw New RangeException('someMessage');
    }
}
