<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:25.
 */
class RuntimeExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException RuntimeException
     * @expectedExceptionMessage someMessage
     */
    public function testRuntimeException()
    {
        throw New RuntimeException('someMessage');
    }
}
