<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:26.
 */
class UnderflowExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException UnderflowException
     * @expectedExceptionMessage someMessage
     */
    public function testUnderflowException()
    {
        throw New UnderflowException('someMessage');
    }
}
