<?php namespace CTIMT\MyOrm\Exception\Platform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:26.
 */
class UnexpectedValueExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException UnexpectedValueException
     * @expectedExceptionMessage someMessage
     */
    public function testUnexpectedValueException()
    {
        throw New UnexpectedValueException('someMessage');
    }
}
