<?php namespace CTIMT\MyOrm\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 23:17:27.
 */
class AttributeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Attribute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Model\Attribute::getName
     * @todo   Implement testGetName().
     */
    public function testName()
    {
        $attribute = new Attribute("key", "value");
        $this->assertEquals('key', $attribute->getName());
        $this->assertEquals('key2', $attribute->setName('key2')->getName());
    }

    /**
     * @covers CTIMT\MyOrm\Model\Attribute::getValue
     * @todo   Implement testGetValue().
     */
    public function testValue()
    {
        $attribute = new Attribute("key", "value");
        $this->assertEquals('value', $attribute->getValue());
        $this->assertEquals('value2', $attribute->setValue('value2')->getValue());
    }
}
