<?php namespace CTIMT\MyOrm\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-06 at 19:58:53.
 */
class AttributeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Attribute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Attribute(null,null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function getConstructor(){
        $attribute = New Attribute('key','value');
        $this->assertEquals('key', $attribute->getName());
        $this->assertEquals('va;ie'.$attribute->getValue());
    }


    public function testValue()
    {
        $this->assertEquals('test',$this->object->setValue('test')->getValue());
    }

    public function testName()
    {
        $this->assertEquals('test',$this->object->setName('test')->getName());
    }

}
