<?php namespace CTIMT\MyOrm\Example;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-06 at 23:00:27.
 */
class VenueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Venue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Venue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Example\Venue::getNumericFields
     * @todo   Implement testGetNumericFields().
     */
    public function testGetNumericFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Example\Venue::getStringFields
     * @todo   Implement testGetStringFields().
     */
    public function testGetStringFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Example\Venue::getDataRelationships
     * @todo   Implement testGetDataRelationships().
     */
    public function testGetDataRelationships()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
