<?php namespace CTIMT\MyOrm\Adapter\PaginationStrategy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 23:28:52.
 */
class SqlServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SqlServer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SqlServer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\PaginationStrategy\SqlServer::getDriverName
     * @todo   Implement testGetDriverName().
     */
    public function testGetDriverName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\PaginationStrategy\SqlServer::getTotalResults
     * @todo   Implement testGetTotalResults().
     */
    public function testGetTotalResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CTIMT\MyOrm\Adapter\PaginationStrategy\SqlServer::visitSelect
     * @todo   Implement testVisitSelect().
     */
    public function testVisitSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
