<?php namespace CTIMT\MyOrm\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:21.
 */
class NotFoundTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var NotFound
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * @expectedException \CTIMT\MyOrm\Exception\Http\NotFound
     * @expectedExceptionCode 404
     * @expectedExceptionMessage someMessage
     */
    public function testNotFound()
    {
        throw New NotFound('someMessage');
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
