<?php namespace CTIMT\MyOrm\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:20.
 */
class PaymentRequiredTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PaymentRequired
     */
    protected $object;

    /**
     * @expectedException \CTIMT\MyOrm\Exception\Http\PaymentRequired
     * @expectedExceptionCode 402
     * @expectedExceptionMessage someMessage
     */
    public function testPaymentRequired()
    {
        throw New PaymentRequired('someMessage');
    }
    
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
}
