<?php namespace CTIMT\MyOrm\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:21.
 */
class UnauthorizedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException \CTIMT\MyOrm\Exception\Http\Unauthorized
     * @expectedExceptionCode 401
     * @expectedExceptionMessage someMessage
     */
    public function testUnauthorized()
    {
        throw New Unauthorized('someMessage');
    }
    
}
