<?php namespace CTIMT\MyOrm\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:22.
 */
class UnprocessableEntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException \CTIMT\MyOrm\Exception\Http\UnprocessableEntity
     * @expectedExceptionCode 422
     * @expectedExceptionMessage someMessage
     */
    public function testUnprocessableEntity()
    {
        throw New UnprocessableEntity('someMessage');
    }
}
