<?php namespace CTIMT\MyOrm\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:20.
 */
class UpgradeRequiredTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException \CTIMT\MyOrm\Exception\Http\UpgradeRequired
     * @expectedExceptionCode 426
     * @expectedExceptionMessage someMessage
     */
    public function testUpgradeRequired()
    {
        throw New UpgradeRequired('someMessage');
    }
}
