<?php namespace CTIMT\MyOrm\Tools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 23:17:34.
 */
class ArrayUtilitiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ArrayUtilities
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayUtilities;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CTIMT\MyOrm\Tools\ArrayUtilities::ModifyAndReturn
     * @todo   Implement testModifyAndReturn().
     */
    public function testModifyAndReturn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
