<?php namespace CTIMT\MyOrm\Exception\Visitor\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:24.
 */
class NoValidFieldsExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException NoValidFieldsException
     * @expectedExceptionMessage someMessage
     */
    public function testNoValidFieldsException()
    {
        throw New NoValidFieldsException();
    }
}
