<?php namespace CTIMT\MyOrm\Connection;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 17:35:19.
 */
class ConnectionDecoratorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ConnectionDecorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConnectionDecorator();
    }

    public function testConnectionDecoratorIsPdo(){
        $this->assertInstanceOf('\PDO', $this->object);
    }


    protected function tearDown()
    {
        
    }
}
