<?php namespace CTIMT\MyOrm\Exception\Visitor\DataType;

use CTIMT\MyOrm\Exception\Visitor\DataType\InvalidDataTypeException;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-26 at 22:48:24.
 */
class InvalidDataTypeExceptionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException InvalidDataTypeException
     * @expectedExceptionMessage someMessage
     */
    public function testInvalidDataTypeException()
    {
        throw new InvalidDataTypeException('test','string');
    }
}
